# Site settings
title: Taichi Kato
description: 'Student Software Developer / UI Designer <br> Co-Founder at Questo App '
url: 'https://taichikato.com/portfolio/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Taichi Kato'
  email: tkato.main@gmail.com
  twitter_username: kato_taichi
  facebook_username: kt.taichi
  github_username:  tkato0909
  linkedin_username:  taichikato

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
